name: core_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

    - family: InterMedium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

    - family: InterBold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true

flutter_gen: #assets generator config
  output: lib/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: AppFontFamily